# Generated by Django 3.1.4 on 2021-12-29 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kids.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=200)),
                ('kid_age', models.IntegerField(default=0)),
                ('parent_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999.             Up to 10 digits', regex='^\\d{10}$')], verbose_name='Phone No.')),
                ('parent_email', models.EmailField(max_length=255, verbose_name='Email Address')),
            ],
            bases=(models.Model, kids.models.PhoneValidator),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=500)),
                ('food_group', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Unknown', 'Unknown')], default='Fruit', max_length=30)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kids')),
            ],
        ),
    ]
