# Generated by Django 3.1.4 on 2021-12-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
    ]
