# Generated by Django 3.1.4 on 2021-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_auto_20211229_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='approved_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
