# Generated by Django 3.1.4 on 2021-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_auto_20211229_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
