# Generated by Django 3.1.4 on 2021-12-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='approved_by',
        ),
    ]
