# Generated by Django 4.0 on 2021-12-31 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_auto_20211230_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parent_email',
            field=models.EmailField(max_length=255, verbose_name='Parent Email Address'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='parent_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format 9999999999.             Up to 10 digits', regex='^\\d{10}$')], verbose_name='Parent Phone No.'),
        ),
    ]
